FROM golang:1.24-alpine AS builder
RUN apk add --no-cache gcc g++ musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build ./tokenizer/main.go

FROM alpine:3.19
RUN apk add --no-cache libstdc++ libgcc

WORKDIR /

COPY --from=builder /app/ /

ENTRYPOINT ["/main"]
