FROM golang:1.24-alpine AS builder
RUN apk add --no-cache gcc g++ musl-dev #https://github.com/ollama/ollama/pull/8106

WORKDIR /app
COPY . .

WORKDIR /app/tokenizer

COPY tokenizer/ ./

RUN CGO_ENABLED=1 GOOS=linux go build -o /app/tokenizer-service .

FROM alpine:3.19
RUN apk add --no-cache libstdc++ libgcc # ? #https://github.com/ollama/ollama/pull/8106

WORKDIR /app

COPY --from=builder /app/tokenizer-service /app/tokenizer-service

ENTRYPOINT ["/app/tokenizer-service"]
