FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY core/go.mod core/go.sum ./core/
COPY libs libs
WORKDIR /app/core
COPY core/go.mod core/go.sum ./
RUN go mod download

COPY core ./core


COPY core/ ./

RUN CGO_ENABLED=0 GOOS=linux go build -o cate

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/core/cate /core

ENTRYPOINT ["/core"]
